app/views/admin/sessions/new.html.erb
config/routes.rb

[fix]routesファイルの修正

---

app/assets/stylesheets/admin/items.scss
app/controllers/admin/items_controller.rb
app/helpers/admin/items_helper.rb
app/models/item.rb
db/migrate/20230616035119_create_items.rb
db/schema.rb
test/controllers/admin/items_controller_test.rb
test/fixtures/items.yml
test/models/item_test.rb

[add]Item(model,controller)

---

app/views/layouts/_footer.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb

・共通のヘッダー、フッターの追加
・customer/登録とログインとログアウトリンク有効化,
・admin/ログアウトリンク有効化

[Add]共通のヘッダー、フッターの追加,customer/登録とログインとログアウトリンク有効化,admin/ログアウトリンク有効化

---

app/views/admin/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/public/registrations/new.html.erb

app/views/layouts/application.html.erbにcontainerクラスを追記
```html:title
<body>
<%= render 'layouts/header' %>
<main>
<div class="container">
<%= yield %>
</div>
</main>
<%= render 'layouts/footer' %>
</body>
```
併せて、他ビューに設置してあったcontainerクラスの削除

[Add]app/views/layouts/application.html.erbにcontainerクラスを追記

---

Gemfile
Gemfile.lock
app/controllers/admin/items_controller.rb
app/models/item.rb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb

###商品新規登録画面
　-データベースのItemGenre情報を参照して、ジャンルの選択肢が表示されるようcontrollerとviewを修正
###商品一覧
　-Item.nameに商品詳細ページへのリンクを設置　※画像表示要確認

[update]app/views/admin/items/new

---

app/controllers/public/customers_controller.rb
app/controllers/public/sessions_controller.rb
app/models/customer.rb
app/views/public/customers/confirm.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb
config/application.rb
config/routes.rb
db/schema.rb

顧客側のページを作成しました。
・顧客のマイページ
・情報変更画面
・退会確認画面
退会済みのCustomerがログインできないようにモデルに制約とsession_controllerに追記

[Add]顧客側のマイページ/情報変更・退会ページ

---

app/controllers/public/customers_controller.rb
app/controllers/public/destinations_controller.rb
app/controllers/public/sessions_controller.rb
app/models/customer.rb
app/views/public/customers/confirm.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb
app/views/public/destinations/edit.html.erb
app/views/public/destinations/index.html.erb
config/application.rb
config/routes.rb
db/schema.rb

Destination pages

---

app/assets/images/svg/nagano_cake.svg
app/assets/images/svg/nagano_icon.svg
app/assets/images/svg/nagano_nav.svg
app/views/layouts/_header.html.erb
app/views/public/homes/about.html.erb
app/views/public/homes/top.html.erb

- app/assets/images/svg
- nagano_cake.svg
- nagano_icon.svg
- nagano_nav
- customer/home
- customer/about
- customer/items

[add]ロゴなどのsvgファイルを追加,[update]customer/home,aboutページへのリンクを有効化

---

Gemfile
Gemfile.lock
app/controllers/public/customers_controller.rb
app/views/layouts/_header.html.erb
app/views/public/customers/confirm.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb
app/views/public/homes/top.html.erb
config/routes.rb
db/schema.rb
db/seeds.rb

Infrastructure

---

app/views/public/orders/show.html.erb

views/public/orders/show
@が抜けていた部分を修正しました。

[Fix]@の不足を修正

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/show.html.erb

/views/admin/orders/show
注文履歴詳細画面を作りました。

[Add]Adminの注文履歴詳細画面

---

app/controllers/public/orders_controller.rb
app/models/cart_item.rb
app/models/order.rb
app/views/public/orders/confirm.html.erb
db/migrate/20230617043459_create_orders.rb
db/schema.rb

- ordersテーブル delivery_fee, default: 800

[update]orders/contorollerを編集,confirmページを編集

---

app/controllers/public/orders_controller.rb
app/views/public/orders/confirm.html.erb

Order complete

---

app/views/public/orders/index.html.erb
app/views/public/orders/show.html.erb

Order list page

---

app/helpers/application_helper.rb
app/javascript/packs/application.js
app/javascript/stylesheets/logo_icon.css
app/views/layouts/_header.html.erb

[add]nagano_nav.svgを表示

---

app/views/admin/items/index.html.erb
app/views/admin/items/show.html.erb
db/schema.rb

[fix]price

---

app/views/admin/item_genres/index.html.erb

[fixed]genre layouts

---

app/models/destination.rb
app/views/public/destinations/index.html.erb

Destinationモデルにバリデーションを追加しました。

Destination pages [Add]バリデーションの追加

---

app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb

[Save]スタイルの調整

---

app/models/cart_item.rb
app/views/public/cart_items/index.html.erb
app/views/public/items/_genre_sidebar.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb

- ジャンルサイドバー等変更
- 会員以外のカートへのアイテムの追加制限
- カートへのアイテム数量選択
- カート内商品を１アイテムにつき１０個までの制限

[fixed] layouts

---

app/views/admin/items/_form.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb

[fix]admin/item_layout

---

app/controllers/admin/item_genres_controller.rb
app/models/item_genre.rb
app/views/admin/item_genres/index.html.erb
app/views/layouts/_error_messages.html.erb
app/views/public/items/show.html.erb

Add Errors template

---

config/routes.rb

[add]search_routing

---

app/controllers/public/items_controller.rb
app/views/public/items/_search_form.html.erb
app/views/public/items/search.html.erb
app/views/public/items/show.html.erb

- 商品一覧画面で商品の名前から商品を検索できます
- gemのランサックを使いました。

Add Search customer

---

app/views/public/customers/confirm.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb

[Fix]viewの調整

---

app/views/admin/homes/top.html.erb
app/views/admin/orders/index.html.erb

[Fix]ページネーションのスタイル/viewのスタイル調整

---

app/controllers/public/orders_controller.rb
app/models/destination.rb
app/models/order.rb
app/views/public/orders/index.html.erb

views/public/orders/index-OrdersController
ページネーションの追加
DestinationModel-OrderModel
バリデーションで半角/全角スペースを許可
OrdersController
不足箇所を追記

[Fix]ページネーションの追加/バリデーションに追記/Ordersコントローラの修正

---

app/controllers/admin/items_controller.rb
app/controllers/admin/searchs_controller.rb
app/views/admin/items/_form.html.erb
app/views/admin/items/index.html.erb

Admin item errormessage

---

app/controllers/admin/searchs_controller.rb
app/controllers/application_controller.rb
app/controllers/public/item_genres_controller.rb
app/controllers/public/items_controller.rb
app/views/admin/items/index.html.erb
app/views/admin/searchs/_search_form.html.erb
app/views/layouts/_header.html.erb
app/views/public/items/_search_form.html.erb
app/views/public/items/index.html.erb

- before_action にsearch_qメソッドを追加
- adminがログインしている時とそれ以外で、検索結果を分けました。

[update] search bar

---

app/views/public/orders/confirm.html.erb

¥マークを追加し、viewをワイヤーフレームに合わせました。

[Fix]¥マークの追加とviewの調整

---

app/controllers/admin/orders_controller.rb
app/views/admin/customers/order_index.html.erb
app/views/admin/orders/show.html.erb

app/views/admin/orders/show.html.erb
パスの変数を変更
app/controllers/admin/orders_controller.rb
@customerの追記

[Fix]パスの修正とコントローラーに追記

---

app/controllers/public/cart_items_controller.rb
app/models/item.rb
app/views/admin/items/_form.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb

[add]valdation

---

app/controllers/public/sessions_controller.rb
app/models/customer.rb
app/models/item.rb
app/views/layouts/application.html.erb
config/locales/devise.ja.yml
config/locales/ja.yml

Itemモデルのgenre_idのバリデーションを削除しました。
エラーメッセージの日本語化の修正
Deviseのエラーを表示できるようにしました。

Alert message

---

app/views/admin/items/show.html.erb

[fix]admin/items/show ¥マーク

---

app/views/public/customers/show.html.erb
app/views/public/destinations/index.html.erb
app/views/public/items/index.html.erb
app/views/public/items/search.html.erb
app/views/public/items/show.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb
app/views/public/orders/show.html.erb

margin bottom

---

app/controllers/public/cart_items_controller.rb
app/views/layouts/application.html.erb
app/views/public/cart_items/index.html.erb

[add]data confirm, and changed alert,notice color

---

app/controllers/public/orders_controller.rb
app/views/admin/orders/show.html.erb
app/views/public/orders/confirm.html.erb

[Add]確認ダイアログの追加

---

app/models/destination.rb
app/models/order.rb
app/views/public/orders/confirm.html.erb
config/locales/ja.yml

views/orders/confirm
コメントアウトのミスを修正
app/models/order.rb・app/views/public/orders/confirm.html.erb
バリデーションの正規表現に「々」を追加
config/locales/ja.yml
item_imageの日本語エラーメッセージを追加

[Fix]コメントアウト忘れの変更/バリデーションの不足部分を追加

---

app/views/layouts/application.html.erb

[Add]cache-control

---

app/views/admin/searchs/index.html.erb

[fix]リンクの修正
